#!/bin/bash

# global vars
Cm_nm="Boost Week3" ## change to name of command you are practicing

####### arrays #########
# questions
declare -a ques
ques=("Use a command to show all IP addresses"
      "Use a command to clear the screen"
      "Use a command to display the full path to ssh"
      "Use a command to display what the type of ssh is"
      "Use a command to display who is logged in/how they are connected."
      "Use a command to show the user, group names and IDs"
      "Use a command that will show a more verbose who"
      "Use a command that will show effective user name and ID"
      "Use a command that will display short name of all logged in users"
      "Use a command that will display a summary of last logged in users"
      "Use a command what will exit the current program, login or shell"
      "Use the ls command and pipe it to a command that lets you scroll"
      "Spell out the key combination that lets you interrupt a program"
      "Spell out the key combination that sends \"end of data/file\""
      "Use apt to install openssh-server"
      "Use vboxmanage to run the VM named rwx as headless"
      "Use vboxmanage to list all running VMs"
      "Use vboxmanage to list all VMs"
      "Use vboxmanage to poweroff the headless VM named rwx"
    )

# answers
declare -a answ
answ=("ip a"
      "clear"
      "which ssh"
      "type ssh"
      "who"
      "id"
      "w"
      "whoami"
      "users"
      "last"
      "exit"
      "ls | less"
      "control c"
      "control d"
      "sudo apt install openssh-server"
      "vboxmanage startvm rwx --type headless"
      "vboxmanage list runningvms"
      "vboxmanage list vms"
      "vboxmanage controlvm rwx poweroff"
    )
