#!/bin/bash

# cmdprac
# Written by: Joe Burgess
#
# This script is used for practicing commands.
# The questions and answers are stored in arrays in the cmdprac-arrs
# directory.

# Source to ques and answ arrays
# You can change apt-cmdprac to what ever you would like
source ./cmdprac-arrs/apt-cmdprac

# Create array for random index numbers
declare -a rand_arr=()

##### functions #######

# intro screen
intro_scrn() {
  clear
  toilet "${Cm_nm} command practice"
  echo "Welcome to cmdprac! This script will help you learn"
  echo "common ${Cm_nm} commands. Enjoy!"
  echo "Press enter to continue"
  read -r
  clear
  ask_quest
}

# exit screen
exit_scrn() {
  clear
  toilet "Good Job!"
  echo "Your ${Cm_nm} wizardry skills have increased!"
  echo "Would you like to try again? (y)es (n)o"
  read -r exita

  if [ "${exita}" == "y" ]; then
    clear
    toilet "WooHoo!"
    echo "Lets do some more ${Cm_nm} learning!"
    echo "Press enter to continue"
    read -r
    clear
    ask_quest

    else
      toilet "Have a good day!"
    exit
  fi
}

ask_quest() {

  # ask questions
  for idx in "${rand_arr[@]}"; do
    answr=""
    x=true
    y=3

    while [ "$x" == true ]; do
      echo
      echo "${ques[$idx]}"
      read -r answr

      # check answer
      if [ "${answr}" == "${answ[idx]}" ]; then
        echo "Correct!"
        x=false
      else
          echo "Answer is not correct. Try again"
          ((y=y-1))
          echo "Tries left: " "${y}"
      fi

      # check number of tries and give answer
      if [[ "$y" -eq 0 ]]; then
        echo
        echo "The correct answer is \"${answ[idx]}\""
        y=3
        echo "Press enter to try again"
        read -r
        clear
      fi
    done
  done
  exit_scrn
}

# iterate through each ele of ques array and store the index in rand_arr
for ele in "${!ques[@]}"; do
  rand_arr+=("${ele}")
done

# Shuffle rand_arr to randomize the elements
rand_arr=( $(shuf -e "${rand_arr[@]}") )

# Load intro screen
intro_scrn
