#!/bin/bash

# Questions and answers for apt

# global vars
Cm_nm="apt" ## change to name of command you are practicing

####### arrays ######### 
# questions
declare -a ques
ques=("Use apt to update the list of available packages and versions" 
      "Use apt to install vim and its dependencys"
      "Use apt to remove neovim and its config files"
      "Use apt to remove neovim but keep its config files"
      "Use apt to remove all unused packages but keep their configs"
      "Use apt to remove all unused packages and their config files"
      "Use apt to list all installed packages"
      "Use apt to list all installed packages that are upgradeable"
      "Use apt to list all available packages but grep for vim"
      "Use apt to upgrade the vim package"
      "Use apt to upgrade all installed packages"
      "Use apt to search all packages that contain the word vim"
      "Use apt to search all packages that start with the word vim"
      "Use apt to show detailed info on the vim package"
      "Use aptitude to show why the vim package is installed"
    )

# answers
declare -a answ
answ=("sudo apt update"
      "sudo apt install vim"
      "sudo apt purge neovim"
      "sudo apt remove neovim"
      "sudo apt autoremove"
      "sudo apt autoremove --purge"
      "sudo apt list --installed"
      "sudo apt list --upgradeable"
      "sudo apt list | grep vim" 
      "sudo apt upgrade vim"
      "sudo apt upgrade"
      "apt search vim"
      "apt search ^vim"
      "sudo apt show vim"
      "aptitude why vim"
    )
